version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: ctf-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: ctf-platform
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./setup-database.js:/docker-entrypoint-initdb.d/setup-database.js:ro
    networks:
      - ctf-network

  # Next.js Application
  ctf-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ctf-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/ctf-platform?authSource=admin
      - NEXT_TELEMETRY_DISABLED=1
      # Competition Configuration
      - SELF_FLAG_POINTS=10
      - ATTACK_POINTS=200
      - DEFENSE_PENALTY=50
      - PASSIVE_POINTS_VALUE=1
      - PASSIVE_POINTS_INTERVAL=1200000
      - MAX_SUBMISSIONS_PER_MINUTE=10
      - RATE_LIMIT_WINDOW=60000
      # Public environment variables (accessible in browser)
      - NEXT_PUBLIC_SELF_FLAG_POINTS=10
      - NEXT_PUBLIC_ATTACK_POINTS=200
      - NEXT_PUBLIC_DEFENSE_PENALTY=50
      - NEXT_PUBLIC_PASSIVE_POINTS_VALUE=1
      - NEXT_PUBLIC_PASSIVE_POINTS_INTERVAL=1200000
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - ctf-network
    volumes:
      - ./public/sounds:/app/public/sounds:ro

  # MongoDB Express (Optional - for database management)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: ctf-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - ctf-network

volumes:
  mongodb_data:
    driver: local

networks:
  ctf-network:
    driver: bridge
